const cfg=window.AURA_CONFIG||{};const ready=cfg.url&&cfg.publishableKey&&!cfg.url.includes("YOUR_")&&!cfg.publishableKey.includes("YOUR_");let db=null,currentProducts=[];const $=id=>document.getElementById(id);function msg(id,t){$(id).textContent=t||""}
if(ready)db=window.supabase.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}});
function requireReady(){if(!ready){msg("login-msg","Önce supabase-config.js içine Supabase URL ve Publishable Key eklenmeli.");return false}return true}
async function isAdmin(){if(!db)return false;const{data:{user}}=await db.auth.getUser();if(!user)return false;const{data,error}=await db.from("site_admins").select("user_id").eq("user_id",user.id).maybeSingle();return !!data&&!error}
async function boot(){if(!requireReady())return;const ok=await isAdmin();if(ok){$("login").hidden=true;$("app").hidden=false;await loadAll()}else{$("login").hidden=false;$("app").hidden=true}}
$("login-form").addEventListener("submit",async e=>{e.preventDefault();if(!requireReady())return;msg("login-msg","Giriş yapılıyor...");const{error}=await db.auth.signInWithPassword({email:$("email").value,password:$("password").value});if(error)msg("login-msg",error.message);else await boot()});
$("logout").addEventListener("click",async()=>{await db.auth.signOut();location.reload()});
document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tabs button").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.tab).classList.add("active")});
async function loadAll(){await loadProducts();await loadSettings()}
async function loadProducts(){const{data,error}=await db.from("products").select("*").order("sort_order").order("created_at");if(error){alert(error.message);return}currentProducts=data||[];$("product-list").innerHTML=currentProducts.map(p=>`<article class="product-row"><div class="thumb" style="background-image:url('${p.image_url||""}')"></div><div><h3>${esc(p.name)}</h3><small>${esc(p.category)} · ${esc(p.price)} ${p.active?'<span class="badge">Yayında</span>':'<span class="badge">Gizli</span>'} ${p.featured?'<span class="badge">Öne çıkan</span>':''}</small></div><div class="actions"><button onclick="editProduct('${p.id}')">Düzenle</button><button class="danger" onclick="deleteProduct('${p.id}')">Sil</button></div></article>`).join("")||"<p>Henüz ürün yok.</p>";$("product-count").textContent=currentProducts.length;$("active-count").textContent=currentProducts.filter(p=>p.active).length;$("featured-count").textContent=currentProducts.filter(p=>p.featured).length}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function openProduct(p={}){$("modal").hidden=false;$("modal-title").textContent=p.id?"Ürünü düzenle":"Yeni ürün";$("product-id").value=p.id||"";$("p-name").value=p.name||"";$("p-category").value=p.category||"Kolye";$("p-price").value=p.price||"";$("p-description").value=p.description||"";$("p-featured").checked=!!p.featured;$("p-active").checked=p.id?p.active!==false:true;$("current-image").textContent=p.image_url?"Mevcut fotoğraf yüklü. Yeni fotoğraf seçerseniz değişir.":""}
window.editProduct=id=>openProduct(currentProducts.find(p=>p.id===id)||{});$("new-product").onclick=()=>openProduct();$("close-modal").onclick=()=>{$("modal").hidden=true};
async function uploadImage(file){if(!file)return"";if(file.size>6*1024*1024)throw new Error("Fotoğraf 6 MB'dan küçük olmalı.");const ext=(file.name.split(".").pop()||"jpg").toLowerCase();const path="products/"+crypto.randomUUID()+"."+ext;const{error}=await db.storage.from("site-images").upload(path,file,{cacheControl:"31536000",contentType:file.type});if(error)throw error;return db.storage.from("site-images").getPublicUrl(path).data.publicUrl}
$("product-form").addEventListener("submit",async e=>{e.preventDefault();msg("product-msg","Kaydediliyor...");try{const id=$("product-id").value;const old=currentProducts.find(p=>p.id===id);const file=$("p-image").files[0];const image=file?await uploadImage(file):(old?.image_url||"");const row={name:$("p-name").value.trim(),category:$("p-category").value,price:$("p-price").value.trim(),description:$("p-description").value.trim(),image_url:image,featured:$("p-featured").checked,active:$("p-active").checked,updated_at:new Date().toISOString()};let error;if(id){({error}=await db.from("products").update(row).eq("id",id))}else{row.sort_order=currentProducts.length;({error}=await db.from("products").insert(row))}if(error)throw error;$("modal").hidden=true;await loadProducts()}catch(e){msg("product-msg",e.message)}});
window.deleteProduct=async id=>{if(!confirm("Bu ürünü silmek istediğinize emin misiniz?"))return;const{error}=await db.from("products").delete().eq("id",id);if(error)alert(error.message);else await loadProducts()};
async function loadSettings(){const{data,error}=await db.from("site_settings").select("*").eq("id","main").maybeSingle();if(error){alert(error.message);return}const s=data||{};$("settings-form").innerHTML=`<h3>İletişim</h3><label>WhatsApp numarası<input name="whatsapp" value="${esc(s.whatsapp)}" placeholder="905xxxxxxxxx"></label><label>Telefon<input name="phone" value="${esc(s.phone)}"></label><label>E-posta<input name="email" value="${esc(s.email)}"></label><label>Instagram adresi<input name="instagram" value="${esc(s.instagram)}" placeholder="https://instagram.com/..."></label><label class="full">Adres<input name="address" value="${esc(s.address)}"></label><h3>Görseller</h3><label>Kapak görseli<input name="hero_image" value="${esc(s.hero_image)}" placeholder="Görsel URL'si"><small>Şimdilik URL. Ürün fotoğrafı doğrudan panelden yüklenir.</small></label><label>Hakkımızda görseli<input name="about_image" value="${esc(s.about_image)}" placeholder="Görsel URL'si"></label><h3 class="full">Ana sayfa metinleri</h3><label>Hikâye başlığı<input name="story_title" value="${esc(s.story_title)}"></label><label>SEO açıklaması<input name="seo_description" value="${esc(s.seo_description)}"></label><label class="full">Hikâye metni<textarea name="story_text" rows="4">${esc(s.story_text)}</textarea></label><button>Site ayarlarını kaydet</button><p id="settings-msg" class="msg full"></p>`}
$("settings-form").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),row=Object.fromEntries(f.entries());row.id="main";row.updated_at=new Date().toISOString();const{error}=await db.from("site_settings").upsert(row);msg("settings-msg",error?error.message:"Kaydedildi ✓");setTimeout(()=>msg("settings-msg",""),2500)}
boot();
